### ISSUE TITLE
Add a flag to KemenyOptimalAggregator to mute pulp logging

### ISSUE THREAD

**Issue by jasper-xian** [castorini/perm-sc#1]
I'd be happy to submit a quick PR for this, I'm making a lot of calls to RRF and would love a flag to silence the calculation logs from pulp.

From what I gather, should only be a few lines of change to add this flag

**Comment by daemon** [comment]
Thanks, that would be great. Does RRF use PuLP? I think it's just `KemenyOptimalAggregator`, right?

**Comment by jasper-xian** [comment]
Yup, I was thinking of just `KemenyOptimalAggregator`

**Comment by daemon** [comment]
Closed by #2, thanks!
